--------------------------------------------------------
--  File created - Sunday-January-14-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ITEMS
--------------------------------------------------------

  CREATE TABLE "C##HAFIZUR"."ITEMS" 
   (	"ITEM_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ITEM_NAME" VARCHAR2(20 BYTE), 
	"ITEM_PRICE" NUMBER(10,2), 
	"ITEM_DESCRIPTION" VARCHAR2(500 BYTE), 
	"IMAGE" VARCHAR2(40 BYTE), 
	"ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CATEGORY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "C##HAFIZUR"."ORDER_ITEMS" 
   (	"ORDER_ID" NUMBER(10,0), 
	"ITEM_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "C##HAFIZUR"."ORDERS" 
   (	"ORDER_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER(10,0), 
	"STORE_ID" NUMBER(10,0), 
	"PAYMENT_ID" NUMBER(10,0), 
	"SUBTOTAL" NUMBER(10,2), 
	"TAX_AMOUNT" NUMBER(10,2), 
	"TOTAL_PRICE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENTS
--------------------------------------------------------

  CREATE TABLE "C##HAFIZUR"."PAYMENTS" 
   (	"PAYMENT_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CREDIT_CARD_NUMBER" NUMBER(20,0), 
	"SECURE_CODE" NUMBER(3,0), 
	"ZIPCODE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REVIEWS
--------------------------------------------------------

  CREATE TABLE "C##HAFIZUR"."REVIEWS" 
   (	"REVIEW_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER(10,0), 
	"ITEM_ID" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STORES
--------------------------------------------------------

  CREATE TABLE "C##HAFIZUR"."STORES" 
   (	"STORE_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STORE_NAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"ZIPCODE" NUMBER(10,0), 
	"STAFF_NUMBER" NUMBER(10,0), 
	"IMAGE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##HAFIZUR"."USERS" 
   (	"USER_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FIRST_NAME" VARCHAR2(40 BYTE), 
	"LAST_NAME" VARCHAR2(40 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" NUMBER(10,0), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"ADMIN_ROLE" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITEM_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##HAFIZUR"."ITEM_ID_PK" ON "C##HAFIZUR"."ITEMS" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDER_ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##HAFIZUR"."ORDER_ITEMS_PK" ON "C##HAFIZUR"."ORDER_ITEMS" ("ORDER_ID", "ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDER_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##HAFIZUR"."ORDER_ID_PK" ON "C##HAFIZUR"."ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##HAFIZUR"."PAYMENT_ID_PK" ON "C##HAFIZUR"."PAYMENTS" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REVIEW_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##HAFIZUR"."REVIEW_ID_PK" ON "C##HAFIZUR"."REVIEWS" ("REVIEW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STORE_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##HAFIZUR"."STORE_ID_PK" ON "C##HAFIZUR"."STORES" ("STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADD_UNIQUE_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##HAFIZUR"."ADD_UNIQUE_USER" ON "C##HAFIZUR"."USERS" ("USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##HAFIZUR"."USER_ID_PK" ON "C##HAFIZUR"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "C##HAFIZUR"."ITEMS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ITEMS" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ITEMS" MODIFY ("ITEM_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ITEMS" MODIFY ("ITEM_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ITEMS" MODIFY ("IMAGE" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ITEMS" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ITEMS" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ITEMS" ADD CHECK (ACTIVE IN(0,1)) ENABLE;
  ALTER TABLE "C##HAFIZUR"."ITEMS" ADD CONSTRAINT "ITEM_ID_PK" PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "C##HAFIZUR"."ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_PK" PRIMARY KEY ("ORDER_ID", "ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##HAFIZUR"."ORDER_ITEMS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ORDER_ITEMS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "C##HAFIZUR"."ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ORDERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ORDERS" MODIFY ("STORE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ORDERS" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ORDERS" MODIFY ("SUBTOTAL" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ORDERS" MODIFY ("TAX_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ORDERS" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."ORDERS" ADD CONSTRAINT "ORDER_ID_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENTS
--------------------------------------------------------

  ALTER TABLE "C##HAFIZUR"."PAYMENTS" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."PAYMENTS" MODIFY ("CREDIT_CARD_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."PAYMENTS" MODIFY ("SECURE_CODE" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."PAYMENTS" MODIFY ("ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."PAYMENTS" ADD CONSTRAINT "PAYMENT_ID_PK" PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEWS
--------------------------------------------------------

  ALTER TABLE "C##HAFIZUR"."REVIEWS" MODIFY ("REVIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."REVIEWS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."REVIEWS" ADD CONSTRAINT "REVIEW_ID_PK" PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##HAFIZUR"."REVIEWS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."REVIEWS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STORES
--------------------------------------------------------

  ALTER TABLE "C##HAFIZUR"."STORES" MODIFY ("STORE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."STORES" MODIFY ("STORE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."STORES" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."STORES" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."STORES" MODIFY ("ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."STORES" MODIFY ("IMAGE" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."STORES" ADD CONSTRAINT "STORE_ID_PK" PRIMARY KEY ("STORE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##HAFIZUR"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."USERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."USERS" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##HAFIZUR"."USERS" ADD CHECK (GENDER IS NOT NULL AND GENDER IN('M', 'F')) ENABLE;
  ALTER TABLE "C##HAFIZUR"."USERS" ADD CHECK (ADMIN_ROLE IN(0,1)) ENABLE;
  ALTER TABLE "C##HAFIZUR"."USERS" ADD CONSTRAINT "USER_ID_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##HAFIZUR"."USERS" ADD CONSTRAINT "ADD_UNIQUE_USER" UNIQUE ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
